tinyMCE.addI18n('hu.media_dlg',{
    list:"Lista",
    file:"Fájl/URL",
    advanced:"Haladó",
    general:"Általános",
    title:"Beágyazott Média Beillesztése/Szerkesztése",
    "align_top_left":"Felül balra",
    "align_center":"Középre",
    "align_left":"Balra",
    "align_bottom":"Alul",
    "align_right":"Jobbra",
    "align_top":"Felül",
    "qt_stream_warn":"A streamelt RTSP forrásokat a Haladó fülön lévő QT Forrás mezőhöz kell hozzáadni.\nEgy nem streamelt verziót is hozzá kell adnod a Forrás mezőhöz.",
    qtsrc:"QT Forrás",
    progress:"Folyamat",
    sound:"Hang",
    swstretchvalign:"Függőleges Igazítás Nyújtása",
    swstretchhalign:"Vízszintes Igazítás Nyújtása",
    swstretchstyle:"Stílus Nyújtása",
    scriptcallbacks:"Script Visszahívások",
    "align_top_right":"Felül jobbra",
    uimode:"UI Mód",
    rate:"Sebesség",
    playcount:"Lejátszási Számláló",
    defaultframe:"Alapértelmezett Keret",
    currentposition:"Jelenlegi Pozíció",
    currentmarker:"Jelenlegi Marker",
    captioningid:"Feliratozás ID",
    baseurl:"Alap URL",
    balance:"Egyensúly (Balance)",
    windowlessvideo:"Ablak Nélküli Videó",
    stretchtofit:"Nyújtás Méretre",
    mute:"Némítás",
    invokeurls:"URL-ek Meghívása",
    fullscreen:"Teljes Képernyő",
    enabled:"Engedélyezve",
    autostart:"Automatikus Indítás",
    volume:"Hangerő",
    target:"Cél",
    qtsrcchokespeed:"Szűkítő Sebesség (Choke Speed)",
    href:"HREF",
    endtime:"Befejezési Idő",
    starttime:"Kezdési Idő",
    enablejavascript:"JavaScript Engedélyezése",
    correction:"Nincs Korrekció",
    targetcache:"Cél Cache",
    playeveryframe:"Minden Képkocka Lejátszása",
    kioskmode:"Kioszk Mód",
    controller:"Vezérlő",
    menu:"Menü Mutatása",
    loop:"Ismétlés (Loop)",
    play:"Automatikus Lejátszás",
    hspace:"Vízszintes Térköz",
    vspace:"Függőleges Térköz",
    "class_name":"Osztály",
    name:"Név",
    id:"Azonosító (ID)",
    type:"Típus",
    size:"Méretek",
    preview:"Előnézet",
    "constrain_proportions":"Arányok Megtartása",
    controls:"Vezérlők",
    numloop:"Ismétlések Száma",
    console:"Konzol",
    cache:"Gyorsítótár (Cache)",
    autohref:"Automatikus HREF",
    liveconnect:"SWLiveConnect",
    flashvars:"Flash Változók",
    base:"Alap (Base)",
    bgcolor:"Háttérszín",
    wmode:"WMode",
    salign:"SAlign",
    align:"Igazítás",
    scale:"Méretarány",
    quality:"Minőség",
    shuffle:"Keverés (Shuffle)",
    prefetch:"Előtöltés (Prefetch)",
    nojava:"Nincs Java",
    maintainaspect:"Arányok Fenntartása",
    imagestatus:"Kép Állapota",
    center:"Középre",
    autogotourl:"Automatikus URL Látogatás",
    "shockwave_options":"Shockwave Opciók",
    "rmp_options":"Real Media Player Opciók",
    "wmp_options":"Windows Media Player Opciók",
    "qt_options":"QuickTime Opciók",
    "flash_options":"Flash Opciók",
    hidden:"Rejtett",
    "align_bottom_left":"Alul balra",
    "align_bottom_right":"Alul jobbra",
    "html5_video_options":"HTML5 Videó Opciók",
    altsource1:"Alternatív forrás 1",
    altsource2:"Alternatív forrás 2",
    preload:"Előtöltés",
    poster:"Poszter",
    source:"Forrás",
    "html5_audio_options":"Audió Opciók",
    "preload_none":"Ne Töltse Elő",
    "preload_metadata":"Videó Metaadatok Előtöltése",
    "preload_auto":"Hagyd, hogy a böngésző döntse el",
