tinyMCE.addI18n({hu:{common:{"more_colors":"További színek...",
                            "invalid_data":"Hiba: Érvénytelen értékeket adtál meg. Ezek pirossal vannak jelölve.",
                            "popup_blocked":"Sajnáljuk, de észrevettük, hogy a felugró ablak blokkolód tiltott egy ablakot, ami az alkalmazás működéséhez szükséges. Le kell tiltanod a felugró ablak blokkolását ezen az oldalon, hogy teljes mértékben használni tudd ezt az eszközt.",
                            "clipboard_no_support":"Jelenleg a böngésződ nem támogatja, használj helyette billentyűparancsokat.",
                            "clipboard_msg":"A Másolás/Kivágás/Beillesztés nem elérhető a Mozillában és a Firefoxban.\nSzeretnél több információt kapni erről a problémáról?",
                            "not_set":"-- Nincs Beállítva --",
                            "class_name":"Osztály",
                            browse:"Tallózás",
                            close:"Bezárás",
                            cancel:"Mégse",
                            update:"Frissítés",
                            insert:"Beillesztés",
                            apply:"Alkalmaz",
                            "edit_confirm":"Szeretnéd használni a WYSIWYG módot ehhez a szövegterülethez?",
                            "invalid_data_number":"A(z) {#field} mezőnek számnak kell lennie.",
                            "invalid_data_min":"A(z) {#field} mezőnek nagyobbnak kell lennie, mint {#min}.",
                            "invalid_data_size":"A(z) {#field} mezőnek számnak vagy százalékos értéknek kell lennie.",
                            value:"(érték)"},
                contextmenu:{full:"Teljes",
                             right:"Jobbra",
                             center:"Középre",
                             left:"Balra",
                             align:"Igazítás"},
                insertdatetime:{"day_short":"V,H,K,Sze,Cs,P,Szo,V",
                                "day_long":"Vasárnap,Hétfő,Kedd,Szerda,Csütörtök,Péntek,Szombat,Vasárnap",
                                "months_short":"Jan,Feb,Már,Ápr,Máj,Jún,Júl,Aug,Sze,Okt,Nov,Dec",
                                "months_long":"Január,Február,Március,Április,Május,Június,Július,Augusztus,Szeptember,Október,November,December",
                                "inserttime_desc":"Idő Beillesztése",
                                "insertdate_desc":"Dátum Beillesztése",
                                "time_fmt":"%H:%M:%S",
                                "date_fmt":"%Y-%m-%d"},
                print:{"print_desc":"Nyomtatás"},
                preview:{"preview_desc":"Előnézet"},
                directionality:{"rtl_desc":"Jobbról Balra Irány",
                                "ltr_desc":"Balról Jobbra Irány"},
                layer:{content:"Új réteg...",
                       "absolute_desc":"Abszolút Pozicionálás váltása",
                       "backward_desc":"Hátra Mozgatás",
                       "forward_desc":"Előre Mozgatás",
                       "insertlayer_desc":"Új Réteg Beillesztése"},
                save:{"save_desc":"Mentés",
                      "cancel_desc":"Összes Változtatás Visszavonása"},
                nonbreaking:{"nonbreaking_desc":"Nem Törhető Szóköz Beillesztése"},
                iespell:{download:"Az ieSpell nem észlelhető. Szeretnéd telepíteni most?",
                         "iespell_desc":"Helyesírás-ellenőrzés"},
                advhr:{"delta_height":"",
                       "delta_width":"",
                       "advhr_desc":"Vízszintes Vonal Beillesztése"},
                emotions:{"delta_height":"",
                          "delta_width":"",
                          "emotions_desc":"Hangulatjelek"},
                searchreplace:{"replace_desc":"Keresés/Csere",
                               "delta_width":"",
                               "delta_height":"",
                               "search_desc":"Keresés"},
                advimage:{"delta_width":"",
                          "image_desc":"Kép Beillesztése/Szerkesztése",
                          "delta_height":""},
                advlink:{"delta_height":"",
                         "delta_width":"",
                         "link_desc":"Hivatkozás Beillesztése/Szerkesztése"},
                xhtmlxtras:{"attribs_delta_height":"",
                            "attribs_delta_width":"",
                            "ins_delta_height":"",
                            "ins_delta_width":"",
                            "del_delta_height":"",
                            "del_delta_width":"",
                            "acronym_delta_height":"",
                            "acronym_delta_width":"",
                            "abbr_delta_height":"",
                            "abbr_delta_width":"",
                            "cite_delta_height":"",
                            "cite_delta_width":"",
                            "attribs_desc":"Attribútumok Beillesztése/Szerkesztése",
                            "ins_desc":"Beszúrás",
                            "del_desc":"Törlés",
                            "acronym_desc":"Betűszó",
                            "abbr_desc":"Rövidítés",
                            "cite_desc":"Idézet"},
                style:{"delta_height":"",
                       "delta_width":"",
                       desc:"CSS Stílus Szerkesztése"},
                paste:{"plaintext_mode_stick":"A beillesztés most egyszerű szöveg módban van. Kattints újra a visszaváltáshoz a normál módra.",
                       "plaintext_mode":"A beillesztés most egyszerű szöveg módban van. Kattints újra a normál módra váltáshoz. Miután beillesztettél valamit, visszatérsz a normál módra.",
                       "selectall_desc":"Összes Kijelölése",
                       "paste_word_desc":"Beillesztés Wordből",
                       "paste_text_desc":"Beillesztés Egyszerű Szövegként"},
                "paste_dlg":{"word_title":"Használd a Ctrl+V kombinációt a billentyűzeteden a szöveg ablakba illesztéséhez.",
                             "text_linebreaks":"Sortörések Megtartása",
                             "text_title":"Használd a Ctrl+V kombinációt a billentyűzeteden a szöveg ablakba illesztéséhez."},
                table:{"merge_cells_delta_height":"",
                       "merge_cells_delta_width":"",
                       "table_delta_height":"",
                       "table_delta_width":"",
                       "cellprops_delta_height":"",
                       "cellprops_delta_width":"",
                       "rowprops_delta_height":"",
                       "rowprops_delta_width":"",
                       cell:"Cella",
                       col:"Oszlop",
                       row:"Sor",
                       del:"Táblázat Törlése",
                       "copy_row_desc":"Táblázat Sor Másolása",
                       "cut_row_desc":"Táblázat Sor Kivágása",
                       "paste_row_after_desc":"Táblázat Sor Beillesztése Utána",
                       "paste_row_before_desc":"Táblázat Sor Beillesztése Előtte",
                       "props_desc":"Táblázat Tulajdonságai",
                       "cell_desc":"Táblázat Cella Tulajdonságai",
                       "row_desc":"Táblázat Sor Tulajdonságai",
                       "merge_cells_desc":"Táblázat Cellák Egyesítése",
                       "split_cells_desc":"Egyesített Táblázat Cellák Felosztása",
                       "delete_col_desc":"Oszlop Törlése",
                       "col_after_desc":"Oszlop Beszúrása Utána",
                       "col_before_desc":"Oszlop Beszúrása Előtte",
                       "delete_row_desc":"Sor Törlése",
                       "row_after_desc":"Sor Beszúrása Utána",
                       "row_before_desc":"Sor Beszúrása Előtte",
                       desc:"Táblázat Beillesztése/Szerkesztése"},
                autosave:{"warning_message":"Ha visszaállítod az elmentett tartalmat, elveszíted az összes jelenleg a szerkesztőben lévő tartalmat.\n\nBiztosan vissza szeretnéd állítani az elmentett tartalmat?",
                          "restore_content":"Automatikus mentett tartalom visszaállítása.",
                          "unload_msg":"A módosításaid el fognak veszni, ha elnavigálsz erről az oldalról."},
                fullscreen:{desc:"Teljes Képernyős Mód Váltása"},
                media:{"delta_height":"",
                       "delta_width":"",
                       edit:"Beágyazott Média Szerkesztése",
                       desc:"Beágyazott Média Beillesztése/Szerkesztése"},
                fullpage:{desc:"Dokumentum Tulajdonságai",
                          "delta_width":"",
                          "delta_height":""},
                template:{desc:"Előre Meghatározott Sablon Tartalom Beillesztése"},
                visualchars:{desc:"Látható Vezérlőkarakterek Mutatása/Elrejtése"},
                spellchecker:{desc:"Helyesírás-ellenőrző Váltása",
                              menu:"Helyesírás-ellenőrző Beállításai",
                              "ignore_word":"Szó Mellőzése",
                              "ignore_words":"Összes Mellőzése",
                              langs:"Nyelvek",
                              wait:"Kérlek várj...",
                              sug:"Javaslatok",
                              "no_sug":"Nincs Javaslat",
                              "no_mpell":"Nem található elgépelés.",
                              "learn_word":"Szó Megtanulása"},
                pagebreak:{desc:"Oldaltörés Beillesztése Nyomtatáshoz"},
                advlist:{types:"Típusok",
                         def:"Alapértelmezett",
                         "lower_alpha":"Kis Betűs ABC",
                         "lower_greek":"Kis Betűs Görög",
                         "lower_roman":"Kis Betűs Római",
                         "upper_alpha":"Nagy Betűs ABC",
                         "upper_roman":"Nagy Betűs Római",
                         circle:"Kör",
                         disc:"Korong",
                         square:"Négyzet"},
                colors:{"333300":"Sötét olíva",
                        "993300":"Égetett narancs",
                        "000000":"Fekete",
                        "003300":"Sötét zöld",
                        "003366":"Sötét azúrkék",
                        "000080":"Tengerészkék",
                        "333399":"Indigó",
                        "333333":"Nagyon sötét szürke",
                        "800000":"Bíbor",
                        FF6600:"Narancs",
                        "808000":"Olíva",
                        "008000":"Zöld",
                        "008080":"Kékeszöld",
                        "0000FF":"Kék",
                        "666699":"Szürkés kék",
                        "808080":"Szürke",
                        FF0000:"Piros",
                        FF9900:"Borostyán",
                        "99CC00":"Sárgászöld",
                        "339966":"Tengerzöld",
                        "33CCCC":"Türkiz",
                        "3366FF":"Királykék",
                        "800080":"Lila",
                        "999999":"Közepes szürke",
                        FF00FF:"Magenta",
                        FFCC00:"Arany",
                        FFFF00:"Sárga",
                        "00FF00":"Lájszín", // Lime
                        "00FFFF":"Aqua",
                        "00CCFF":"Égkék",
                        "993366":"Barna",
                        C0C0C0:"Ezüst",
                        FF99CC:"Rózsaszín",
                        FFCC99:"Őszibarack",
                        FFFF99:"Világossárga",
                        CCFFCC:"Halványzöld",
                        CCFFFF:"Halvány cián",
                        "99CCFF":"Világos égkék",
                        CC99FF:"Szilva",
                        FFFFFF:"Fehér"},
                aria:{"rich_text_area":"Formázott Szövegterület"},
                wordcount:{words:"Szavak:"},
                visualblocks:{desc:'Blokkelemek mutatása/elrejtése'}}});
