/**
 */

tinyMCE.addI18n('hu.xoopsimagemanager_dlg',{
    tab_general:"Általános",
    tab_appearance:"Megjelenés",
    tab_advanced:"Haladó",
    general:"Általános",
    title:"Cím",
    preview:"Előnézet",
    constrain_proportions:"Arányok megtartása",
    langdir:"Nyelvi irány",
    langcode:"Nyelvi kód",
    long_desc:"Hosszú leírás hivatkozása",
    style:"Stílus",
    classes:"Osztályok",
    ltr:"Balról jobbra",
    rtl:"Jobbról balra",
    id:"Azonosító (ID)",
    map:"Képtérkép (Image map)",
    swap_image:"Kép csere",
    alt_image:"Alternatív kép",
    mouseover:"egér fölé húzásakor",
    mouseout:"egér elmozdításakor",
    misc:"Egyéb",
    example_img:"Megjelenés előnézeti képe",
    missing_alt:"Biztosan folytatni szeretnéd a Kép Leírása (ALT) hozzáadása nélkül? Enélkül a kép esetleg nem lesz hozzáférhető a fogyatékkal élőknek, a szöveges böngészőt használóknak, vagy azoknak, akik kikapcsolt képekkel böngésznek.",
    dialog_title:"Xoops Képkezelő",
    src:"Kép URL-je",
    alt:"Kép leírása",
    list:"Képek listája",
    border:"Szegély",
    dimensions:"Méretek",
    vspace:"Függőleges térköz",
    hspace:"Vízszintes térköz",
    align:"Igazítás",
    align_baseline:"Alapvonal",
    align_top:"Felül",
    align_middle:"Középen",
    align_bottom:"Alul",
    align_texttop:"Szöveg teteje",
    align_textbottom:"Szöveg alja",
    align_left:"Balra",
    align_right:"Jobbra",
    image_list:"Képek listája"
});
