tinyMCE.addI18n('hu.table_dlg',{
    "rules_border":"szegély",
    "rules_box":"doboz",
    "rules_vsides":"függőleges oldalak",
    "rules_rhs":"jobb oldal",
    "rules_lhs":"bal oldal",
    "rules_hsides":"vízszintes oldalak",
    "rules_below":"alul",
    "rules_above":"felül",
    "rules_void":"üres",
    rules:"Szabályok",
    "frame_all":"összes",
    "frame_cols":"oszlopok",
    "frame_rows":"sorok",
    "frame_groups":"csoportok",
    "frame_none":"nincs",
    frame:"Keret",
    caption:"Táblázat Címe",
    "missing_scope":"Biztosan folytatni szeretnéd hatókör megadása nélkül ennél a táblázat fejléc cellánál? E nélkül nehéz lehet a fogyatékkal élőknek megérteni a táblázat tartalmát vagy megjelenített adatait.",
    "cell_limit":"Túllépted a cellák maximális számát ({$cells}).",
    "row_limit":"Túllépted a sorok maximális számát ({$rows}).",
    "col_limit":"Túllépted az oszlopok maximális számát ({$cols}).",
    colgroup:"Oszlop Csoport",
    rowgroup:"Sor Csoport",
    scope:"Hatókör",
    tfoot:"Lábléc (Footer)",
    tbody:"Törzs (Body)",
    thead:"Fejléc (Header)",
    "row_all":"Összes Sor Frissítése a Táblázatban",
    "row_even":"Páros Sorok Frissítése a Táblázatban",
    "row_odd":"Páratlan Sorok Frissítése a Táblázatban",
    "row_row":"Jelenlegi Sor Frissítése",
    "cell_all":"Összes Cella Frissítése a Táblázatban",
    "cell_row":"Összes Cella Frissítése a Sorban",
    "cell_cell":"Jelenlegi Cella Frissítése",
    th:"Fejléc (Header)",
    td:"Adat (Data)",
    summary:"Összefoglalás",
    bgimage:"Háttérkép",
    rtl:"Jobbról Balra",
    ltr:"Balról Jobbra",
    mime:"Cél MIME Típus",
    langcode:"Nyelvi Kód",
    langdir:"Nyelvi Irány",
    style:"Stílus",
    id:"Azonosító (ID)",
    "merge_cells_title":"Táblázat Cellák Egyesítése",
    bgcolor:"Háttérszín",
    bordercolor:"Szegélyszín",
    "align_bottom":"Alul",
    "align_top":"Felül",
    valign:"Függőleges Igazítás",
    "cell_type":"Cella Típus",
    "cell_title":"Táblázat Cella Tulajdonságai",
    "row_title":"Táblázat Sor Tulajdonságai",
    "align_middle":"Középen",
    "align_right":"Jobbra",
    "align_left":"Balra",
    "align_default":"Alapértelmezett",
    align:"Igazítás",
    border:"Szegély",
    cellpadding:"Cella Belső Kitöltés",
    cellspacing:"Cella Térköz",
    rows:"Sorok",
    cols:"Oszlopok",
    height:"Magasság",
    width:"Szélesség",
    title:"Táblázat Beillesztése/Szerkesztése",
    rowtype:"Sor Típus",
    "advanced_props":"Haladó Tulajdonságok",
    "general_props":"Általános Tulajdonságok",
    "advanced_tab":"Haladó",
    "general_tab":"Általános",
    "cell_col":"Összes cella frissítése az oszlopban"
});
