tinyMCE.addI18n('hu.xhtmlxtras_dlg',{
    "attribs_title":"Attribútumok Beillesztése/Szerkesztése",
    "option_rtl":"Jobbról Balra",
    "option_ltr":"Balról Jobbra",
    "insert_date":"Jelenlegi Dátum/Idő Beillesztése",
    remove:"Eltávolítás",
    "title_cite_element":"Idézet Elem",
    "title_abbr_element":"Rövidítés Elem",
    "title_acronym_element":"Betűszó Elem",
    "title_del_element":"Törlés Elem",
    "title_ins_element":"Beszúrás Elem",
    "fieldset_events_tab":"Elem Események",
    "fieldset_attrib_tab":"Elem Attribútumok",
    "fieldset_general_tab":"Általános Beállítások",
    "events_tab":"Események",
    "attrib_tab":"Attribútumok",
    "general_tab":"Általános",
    "attribute_attrib_tab":"Attribútumok",
    "attribute_events_tab":"Események",
    "attribute_label_accesskey":"Elérési Kulcs (AccessKey)",
    "attribute_label_tabindex":"Lap-index (TabIndex)",
    "attribute_label_langcode":"Nyelv",
    "attribute_option_rtl":"Jobbról Balra",
    "attribute_option_ltr":"Balról Jobbra",
    "attribute_label_langdir":"Szöveg Iránya",
    "attribute_label_datetime":"Dátum/Idő",
    "attribute_label_cite":"Idézet",
    "attribute_label_style":"Stílus",
    "attribute_label_class":"Osztály",
    "attribute_label_id":"Azonosító (ID)",
    "attribute_label_title":"Cím (Title)"
});
