tinyMCE.addI18n('hu.advlink_dlg',{
    "target_name":"Cél Név (Target Name)",
    classes:"Osztályok",
    style:"Stílus",
    id:"Azonosító (ID)",
    "popup_position":"Pozíció (X/Y)",
    langdir:"Nyelvi Irány",
    "popup_size":"Méret",
    "popup_dependent":"Függő (Csak Mozilla/Firefox)",
    "popup_resizable":"Átméretezhető Ablak Készítése",
    "popup_location":"Hely Sáv Megjelenítése",
    "popup_menubar":"Menü Sáv Megjelenítése",
    "popup_toolbar":"Esztközsávok Megjelenítése",
    "popup_statusbar":"Állapot Sáv Megjelenítése",
    "popup_scrollbars":"Görgetősávok Megjelenítése",
    "popup_return":"\'return false\' Beillesztése",
    "popup_name":"Ablak Név",
    "popup_url":"Felugró Ablak URL-je",
    popup:"JavaScript Felugró Ablak",
    "target_blank":"Megnyitás Új Ablakban",
    "target_top":"Megnyitás Felső Keretben (Minden Keretet Lecserél)",
    "target_parent":"Megnyitás Szülő Ablakban/Keretben",
    "target_same":"Megnyitás Ebben az Ablakban/Keretben",
    "anchor_names":"Horgonyok",
    "popup_opts":"Opciók",
    "advanced_props":"Haladó Tulajdonságok",
    "event_props":"Események",
    "popup_props":"Felugró Ablak Tulajdonságai",
    "general_props":"Általános Tulajdonságok",
    "advanced_tab":"Haladó",
    "events_tab":"Események",
    "popup_tab":"Felugró Ablak",
    "general_tab":"Általános",
    list:"Hivatkozások Listája",
    "is_external":"Az általad megadott URL külső hivatkozásnak tűnik. Szeretnéd hozzáadni a szükséges http:// előtagot?",
    "is_email":"Az általad megadott URL e-mail címnek tűnik. Szeretnéd hozzáadni a szükséges mailto: előtagot?",
    titlefield:"Cím (Title)",
    target:"Cél (Target)",
    url:"Hivatkozás URL-je",
    title:"Hivatkozás Beillesztése/Szerkesztése",
    "link_list":"Hivatkozások Listája",
    rtl:"Jobbról Balra",
    ltr:"Balról Jobbra",
    accesskey:"Elérési Kulcs (AccessKey)",
    tabindex:"Lap-index (TabIndex)",
    rev:"Kapcsolat a Cél és az Oldal között",
    rel:"Kapcsolat az Oldal és a Cél között",
    mime:"Cél MIME Típus",
    encoding:"Cél Karakterkódolása",
    langcode:"Nyelvi Kód",
    "target_langcode":"Cél Nyelv",
    width:"Szélesség",
    height:"Magasság"
});
