tinyMCE.addI18n('hu.style_dlg',{
    "text_lineheight":"Sormagasság",
    "text_variant":"Változat (Variant)",
    "text_style":"Stílus",
    "text_weight":"Vastagság",
    "text_size":"Méret",
    "text_font":"Betűtípus",
    "text_props":"Szöveg",
    "positioning_tab":"Pozicionálás",
    "list_tab":"Lista",
    "border_tab":"Szegély",
    "box_tab":"Doboz (Box)",
    "block_tab":"Blokk",
    "background_tab":"Háttér",
    "text_tab":"Szöveg",
    apply:"Alkalmaz",
    toggle_insert_span:"Span Beszúrása a Kijelöléshez",
    title:"CSS Stílus Szerkesztése",
    clip:"Kivágás (Clip)",
    placement:"Elhelyezés (Placement)",
    overflow:"Túlcsordulás (Overflow)",
    zindex:"Z-index",
    visibility:"Láthatóság",
    "positioning_type":"Típus",
    position:"Pozíció",
    "bullet_image":"Felsorolás Jel Képe",
    "list_type":"Típus",
    color:"Szín",
    height:"Magasság",
    width:"Szélesség",
    style:"Stílus",
    margin:"Margó",
    left:"Bal",
    bottom:"Alsó",
    right:"Jobb",
    top:"Felső",
    same:"Ugyanaz Mindenhol",
    padding:"Kitöltés (Padding)",
    "box_clear":"Törlés (Clear)",
    "box_float":"Úsztatás (Float)",
    "box_height":"Magasság",
    "box_width":"Szélesség",
    "block_display":"Megjelenítés (Display)",
    "block_whitespace":"Fehér Térköz (Whitespace)",
    "block_text_indent":"Szöveg Behúzás",
    "block_text_align":"Szöveg Igazítás",
    "block_vertical_alignment":"Függőleges Igazítás",
    "block_letterspacing":"Karakter Térköz",
    "block_wordspacing":"Szó Térköz",
    "background_vpos":"Függőleges Pozíció",
    "background_hpos":"Vízszintes Pozíció",
    "background_attachment":"Rögzítés (Attachment)",
    "background_repeat":"Ismétlés (Repeat)",
    "background_image":"Háttérkép",
    "background_color":"Háttérszín",
    "text_none":"Nincs",
    "text_blink":"Villogás (Blink)",
    "text_case":"Eset (Case)",
    "text_striketrough":"Áthúzás",
    "text_underline":"Aláhúzás",
    "text_overline":"Föléhúzás (Overline)",
    "text_decoration":"Díszítés (Decoration)",
    "text_color":"Szín",
    text:"Szöveg",
    background:"Háttér",
    block:"Blokk",
    box:"Doboz (Box)",
    border:"Szegély",
    list:"Lista"
});
