tinyMCE.addI18n('hu.fullpage_dlg',{
    title:"Dokumentum Tulajdonságai",
    "meta_tab":"Általános",
    "appearance_tab":"Megjelenés",
    "advanced_tab":"Haladó",
    "meta_props":"Meta Információ",
    langprops:"Nyelv és Kódolás",
    "meta_title":"Cím",
    "meta_keywords":"Kulcsszavak",
    "meta_description":"Leírás",
    "meta_robots":"Robotok",
    doctypes:"Dokumentumtípus (Doctype)",
    langcode:"Nyelvi Kód",
    langdir:"Nyelvi Irány",
    ltr:"Balról Jobbra",
    rtl:"Jobbról Balra",
    "xml_pi":"XML Deklaráció",
    encoding:"Karakterkódolás",
    "appearance_bgprops":"Háttér Tulajdonságai",
    "appearance_marginprops":"Szövegtörzs Margók",
    "appearance_linkprops":"Hivatkozás Színek",
    "appearance_textprops":"Szöveg Tulajdonságai",
    bgcolor:"Háttérszín",
    bgimage:"Háttérkép",
    "left_margin":"Bal Margó",
    "right_margin":"Jobb Margó",
    "top_margin":"Felső Margó",
    "bottom_margin":"Alsó Margó",
    "text_color":"Szövegszín",
    "font_size":"Betűméret",
    "font_face":"Betűtípus",
    "link_color":"Hivatkozás Színe",
    "hover_color":"Hover Szín (rámutatáskor)",
    "visited_color":"Meglátogatott Hivatkozás Színe",
    "active_color":"Aktív Hivatkozás Színe",
    textcolor:"Szín",
    fontsize:"Betűméret",
    fontface:"Betűcsalád",
    "meta_index_follow":"Indexelés és Hivatkozások Követése",
    "meta_index_nofollow":"Indexelés és Hivatkozások NEM Követése",
    "meta_noindex_follow":"Ne Indexelje, de Kövesse a Hivatkozásokat",
    "meta_noindex_nofollow":"Ne Indexelje és Hivatkozásokat SEM Kövesse",
    "appearance_style":"Stíluslap és Stílus Tulajdonságok",
    stylesheet:"Stíluslap (Stylesheet)",
    style:"Stílus",
    author:"Szerző",
    copyright:"Szerzői Jog (Copyright)",
    add:"Új Elem Hozzáadása",
    remove:"Kijelölt Elem Eltávolítása",
    moveup:"Kijelölt Elem Feljebb Mozgatása",
    movedown:"Kijelölt Elem Lejjebb Mozgatása",
    "head_elements":"Head Elemek",
    info:"Információ",
    "add_title":"Cím Elem",
    "add_meta":"Meta Elem",
    "add_script":"Script Elem",
    "add_style":"Stílus Elem",
    "add_link":"Link Elem",
    "add_base":"Base Elem",
    "add_comment":"Komment Csomópont",
    "title_element":"Cím Elem",
    "script_element":"Script Elem",
    "style_element":"Stílus Elem",
    "base_element":"Base Elem",
    "link_element":"Link Elem",
    "meta_element":"Meta Elem",
    "comment_element":"Komment",
    src:"Forrás (Source)",
    language:"Nyelv",
    href:"HREF",
    target:"Cél (Target)",
    type:"Típus",
    charset:"Karakterkészlet (Charset)",
    defer:"Defer",
    media:"Média",
    properties:"Tulajdonságok",
    name:"Név",
    value:"Érték",
    content:"Tartalom",
    rel:"Rel",
    rev:"Rev",
    hreflang:"HREF Nyelv",
    "general_props":"Általános",
    "advanced_props":"Haladó"
});
