tinyMCE.addI18n('hu.advimage_dlg',{
    "image_list":"Képek listája",
    "align_right":"Jobbra",
    "align_left":"Balra",
    "align_textbottom":"Szöveg alja",
    "align_texttop":"Szöveg teteje",
    "align_bottom":"Alul",
    "align_middle":"Középen",
    "align_top":"Felül",
    "align_baseline":"Alapvonal",
    align:"Igazítás",
    hspace:"Vízszintes Térköz",
    vspace:"Függőleges Térköz",
    dimensions:"Méretek",
    border:"Szegély",
    list:"Képek Listája",
    alt:"Kép Leírása (ALT)",
    src:"Kép URL-je",
    "dialog_title":"Kép Beillesztése/Szerkesztése",
    "missing_alt":"Biztosan folytatni szeretnéd a Kép Leírása (ALT) hozzáadása nélkül? Enélkül a kép esetleg nem lesz hozzáférhető a fogyatékkal élőknek, a szöveges böngészőt használóknak, vagy azoknak, akik kikapcsolt képekkel böngésznek.",
    "example_img":"Megjelenés Előnézeti Képe",
    misc:"Egyéb",
    mouseout:"Egér Elmozdításakor",
    mouseover:"Egér Fölé Húzásakor",
    "alt_image":"Alternatív Kép",
    "swap_image":"Kép Csere",
    map:"Képtérkép (Image Map)",
    id:"Azonosító (ID)",
    rtl:"Jobbról Balra",
    ltr:"Balról Jobbra",
    classes:"Osztályok",
    style:"Stílus",
    "long_desc":"Hosszú Leírás Hivatkozása",
    langcode:"Nyelvi Kód",
    langdir:"Nyelvi Irány",
    "constrain_proportions":"Arányok Megtartása",
    preview:"Előnézet",
    title:"Cím (Title)",
    general:"Általános",
    "tab_advanced":"Haladó",
    "tab_appearance":"Megjelenés",
    "tab_general":"Általános",
    width:"Szélesség",
    height:"Magasság"
});
