tinyMCE.addI18n('hu.advanced',{
    "underline_desc":"Aláhúzás (Ctrl+U)",
    "italic_desc":"Dőlt (Ctrl+I)",
    "bold_desc":"Félkövér (Ctrl+B)",
    dd:"Definíció Leírása (DD)",
    dt:"Definíció Fogalma (DT)",
    samp:"Kód Minta",
    code:"Kód",
    blockquote:"Blokkos Idézet",
    h6:"Címsor 6",
    h5:"Címsor 5",
    h4:"Címsor 4",
    h3:"Címsor 3",
    h2:"Címsor 2",
    h1:"Címsor 1",
    pre:"Előre Formázott",
    address:"Cím",
    div:"DIV",
    paragraph:"Bekezdés",
    block:"Formátum",
    fontdefault:"Betűcsalád",
    "font_size":"Betűméret",
    "style_select":"Stílusok",
    "anchor_delta_height":"",
    "anchor_delta_width":"",
    "charmap_delta_height":"",
    "charmap_delta_width":"",
    "colorpicker_delta_height":"",
    "colorpicker_delta_width":"",
    "link_delta_height":"",
    "link_delta_width":"",
    "image_delta_height":"",
    "image_delta_width":"",
    "more_colors":"További Színek...",
    "toolbar_focus":"Ugrás az eszköztárhoz - Alt+Q, Ugrás a szerkesztőhöz - Alt-Z, Ugrás az elemeléréshez - Alt-X",
    newdocument:"Biztosan törölni szeretnéd az összes tartalmat?",
    path:"Elérési Út",
    "clipboard_msg":"A Másolás/Kivágás/Beillesztés nem elérhető a Mozillában és a Firefoxban.\nSzeretnél több információt kapni erről a problémáról?",
    "blockquote_desc":"Blokkos Idézet",
    "help_desc":"Súgó",
    "newdocument_desc":"Új Dokumentum",
    "image_props_desc":"Kép Tulajdonságai",
    "paste_desc":"Beillesztés (Ctrl+V)",
    "copy_desc":"Másolás (Ctrl+C)",
    "cut_desc":"Kivágás (Ctrl+X)",
    "anchor_desc":"Horgony Beillesztése/Szerkesztése",
    "visualaid_desc":"Útmutatók/Láthatatlan Elemek Mutatása/Elrejtése",
    "charmap_desc":"Speciális Karakter Beszúrása",
    "backcolor_desc":"Háttérszín Kiválasztása",
    "forecolor_desc":"Szövegszín Kiválasztása",
    "custom1_desc":"A Te Egyedi Leírásod Itt",
    "removeformat_desc":"Formázás Eltávolítása",
    "hr_desc":"Vízszintes Vonal Beszúrása",
    "sup_desc":"Felső Index",
    "sub_desc":"Alsó Index",
    "code_desc":"HTML Forráskód Szerkesztése",
    "cleanup_desc":"Rendetlen Kód Tisztítása",
    "image_desc":"Kép Beillesztése/Szerkesztése",
    "unlink_desc":"Hivatkozás Eltávolítása",
    "link_desc":"Hivatkozás Beillesztése/Szerkesztése",
    "redo_desc":"Ismét (Ctrl+Y)",
    "undo_desc":"Visszavonás (Ctrl+Z)",
    "indent_desc":"Behúzás Növelése",
    "outdent_desc":"Behúzás Csökkentése",
    "numlist_desc":"Számozott Lista Beszúrása/Eltávolítása",
    "bullist_desc":"Felsorolás Beszúrása/Eltávolítása",
    "justifyfull_desc":"Teljes Igazítás",
    "justifyright_desc":"Jobbra Igazítás",
    "justifycenter_desc":"Középre Igazítás",
    "justifyleft_desc":"Balra Igazítás",
    "striketrough_desc":"Áthúzott",
    "help_shortcut":"Nyomj ALT-F10-et az eszköztárhoz. Nyomj ALT-0-t a súgóhoz",
    "rich_text_area":"Formázott Szövegterület",
    "shortcuts_desc":"Kisegítő Lehetőségek Súgó",
    toolbar:"Eszköztár"
});
