tinyMCE.addI18n('hu.advanced_dlg', {
    "link_list":"Hivatkozások Listája",
    "link_is_external":"Az általad megadott URL külső hivatkozásnak tűnik. Szeretnéd hozzáadni a szükséges http:// előtagot?",
    "link_is_email":"Az általad megadott URL e-mail címnek tűnik. Szeretnéd hozzáadni a szükséges mailto: előtagot?",
    "link_titlefield":"Cím",
    "link_target_blank":"Hivatkozás Megnyitása Új Ablakban",
    "link_target_same":"Hivatkozás Megnyitása Ugyanabban az Ablakban",
    "link_target":"Cél",
    "link_url":"Hivatkozás URL-je",
    "link_title":"Hivatkozás Beillesztése/Szerkesztése",
    "image_align_right":"Jobbra",
    "image_align_left":"Balra",
    "image_align_textbottom":"Szöveg alja",
    "image_align_texttop":"Szöveg teteje",
    "image_align_bottom":"Alul",
    "image_align_middle":"Középen",
    "image_align_top":"Felül",
    "image_align_baseline":"Alapvonal",
    "image_align":"Igazítás",
    "image_hspace":"Vízszintes Térköz",
    "image_vspace":"Függőleges Térköz",
    "image_dimensions":"Méretek",
    "image_alt":"Kép Leírása",
    "image_list":"Képek Listája",
    "image_border":"Szegély",
    "image_src":"Kép URL-je",
    "image_title":"Kép Beillesztése/Szerkesztése",
    "charmap_title":"Speciális Karakter Kiválasztása",
    "charmap_usage":"Használd a bal és jobb nyilakat a navigáláshoz.",
    "colorpicker_name":"Név:",
    "colorpicker_color":"Szín:",
    "colorpicker_named_title":"Elnevezett Színek",
    "colorpicker_named_tab":"Elnevezett",
    "colorpicker_palette_title":"Paletta Színek",
    "colorpicker_palette_tab":"Paletta",
    "colorpicker_picker_title":"Színválasztó",
    "colorpicker_picker_tab":"Választó",
    "colorpicker_title":"Szín Kiválasztása",
    "code_wordwrap":"Szótörés (Word Wrap)",
    "code_title":"HTML Forráskód Szerkesztő",
    "anchor_name":"Horgony Név",
    "anchor_title":"Horgony Beillesztése/Szerkesztése",
    "about_loaded":"Betöltött Pluginok",
    "about_version":"Verzió",
    "about_author":"Szerző",
    "about_plugin":"Plugin",
    "about_plugins":"Pluginok",
    "about_license":"Licenc",
    "about_help":"Segítség",
    "about_general":"Névjegy",
    "about_title":"TinyMCE Névjegy",
    "anchor_invalid":"Kérlek, adj meg egy érvényes horgony nevet.",
    "accessibility_help":"Kisegítő Lehetőségek Segítsége",
    "accessibility_usage_title":"Általános Használat",
    "invalid_color_value":"Érvénytelen szín érték",
    "":""
});
